### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by BrokenPen** [BrokenPen/EmbeddedSystem-Lego-ev3#2]
# temp

2017 May 10 finish mqtt.md install!!

github EmbeddedSystem-Lego-ev3

#### 1. hardware (./hardware/hardware.md#hardware)
- [x] main
- [x] computer (./hardware/hardware.md#computer)
- [x] lego-ev3 (./hardware/hardware.md#lego-ev3)

#### 2. operate-system (./operate-system/operate-system.md#operate-system)
- [x] main
- [x] prepare-os (./operate-system/operate-system.md#prepare-os)
- [x] prepare ev3dev (./operate-system/operate-system.md#prepare-ev3dev)

#### 3. What is Embeed System (./embedded-system.md)
- [x] main
- [x] no sub-index

#### 4. Setup ev3dev (./embedded-system/ev3dev.md#ev3dev)
- [x] main
- [x] no sub-index

#### 5. Hello World ev3dev (./embedded-system/hello-world-ev3dev.md#hello-world-ev3dev)
- [x] main
- [x] connect ev3 via usb (./embedded-system/hello-world-ev3dev.md#connect-ev3-via-usb)
- [x] share Internet to ev3dev (./embedded-system/hello-world-ev3dev.md#ev3dev-connect-to-the--
- [x] internet-via-usb)
- [?] create wifi hotspot (./embedded-system/hello-world-ev3dev.md#use-network-manager) <- need photo of brick configuration
- [x] ssh (./embedded-system/hello-world-ev3dev.md#ssh)
- [x] update-ev3dev (./embedded-system/hello-world-ev3dev.md#update-ev3dev)
    

#### 6. sysfs (./embedded-system/sysfs.md)
- [x] main
- [x] programming (./embedded-system/sysfs.md#programming)
- [x] shell script (./embedded-system/sysfs.md#shell-script)
- [x] c-language (./embedded-system/sysfs.md#c-language)
- [x] lego-sensor (./embedded-system/sysfs-lego-sensor.md#sysfs-lego-sensor)

### include in course.READ.md (index) ?
- out ./code/mqtt/nodemcu/readme.md
- out ./code/mqtt/nanopi_m1/readme.md
- [ ] ./code/README.md
- [x] ./course/embedded-system.md
- [x] ./course/mqtt.md
- [x] ./course/README.md <- index
- [x] ./course/extra.md
- [x] ./course/hardware/hardware.md
- [x] ./course/embedded-system/hello-world-ev3dev.md
- [x] ./course/embedded-system/sysfs.md
- [x] ./course/embedded-system/sysfs-lego-sensor.md
- [x] ./course/embedded-system/ev3dev.md
- [ ] ./course/embedded-system/sysfs-continue.md
- [x] ./course/operate-system/bootable-usb.md
- [x] ./course/operate-system/virtualbox.md
- [x] ./course/operate-system/operate-system.md
- out ./README.md <- git repo root README.md

- [x] ./course/arduino.md
- [x] ./course/esp8266.md

#### presentation 
- [ ] ./presentation/copy-cat.md
- [ ] ./extra.md

---

![](https://github.com/BrokenPen/EmbeddedSystem-Lego-ev3/blob/master/temp/work-require.png?raw=true)
## School Presentation
- [ ] github EmbeddedSystem-Lego-ev3
- [ ] poster
- [ ] present .odp
- [ ] video

 [ ] or [x] (incomplete or complete)

---

Wifi connection part 

https://github.com/BrokenPen/EmbeddedSystem-Lego-ev3/blob/master/course/embedded-system/ev3dev.md#ev3dev
